name = "checklist-diario-push"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Roda todo minuto. Plano gratuito da Cloudflare inclui cron triggers.
[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "3e5eba5c63854054b83e900a3359538e"

[[d1_databases]]
binding = "DB"
database_name = "checklist-diario-db"
database_id = "d8bcac5c-00e2-4e9b-b131-94026e506b56"

[vars]
VAPID_PUBLIC_KEY = "BGxLxsYdfeBxWWcN37VXpQrfOF5ME3a23FxJSwsayVup0N0ub6OVpDFi8-U6RwvAKLOu1f_BfqsdAaBbIb2Zmsg"
VAPID_SUBJECT = "mailto:carloseduardomilanez@gmail.com"
GOOGLE_CLIENT_ID = "848411907261-lj6tec41plj1cflfgbrtiselhi3vljtu.apps.googleusercontent.com"
